[versions]
lib-cache = "3.0.0"
lib-graphql = "3.0.0"
lib-http-client = "4.0.0"
lib-license = "4.0.0"
lib-router = "4.0.0"
lib-static = "3.0.0"
lib-explorer = "5.0.0-SNAPSHOT"

[libraries]
lib-cache = { module = "com.enonic.lib:lib-cache", version.ref = "lib-cache" }
lib-graphql = { module = "com.enonic.lib:lib-graphql", version.ref = "lib-graphql" }
lib-http-client = { module = "com.enonic.lib:lib-http-client", version.ref = "lib-http-client" }
lib-license = { module = "com.enonic.lib:lib-license", version.ref = "lib-license" }
lib-router = { module = "com.enonic.lib:lib-router", version.ref = "lib-router" }
lib-static = { module = "com.enonic.lib:lib-static", version.ref = "lib-static" }
lib-explorer = { module = "com.enonic.lib:lib-explorer", version.ref = "lib-explorer" }
