import {toStr} from '@enonic/js-utils';

import {
	GQL_OBJECT_TYPE_AGGREGATION_COUNT_NAME,
	GQL_OBJECT_TYPE_AGGREGATION_DATE_HISTOGRAM_NAME,
	GQL_OBJECT_TYPE_AGGREGATION_DATE_RANGE_NAME,
	GQL_OBJECT_TYPE_AGGREGATION_GEO_DISTANCE_NAME,
	GQL_OBJECT_TYPE_AGGREGATION_MAX_NAME,
	GQL_OBJECT_TYPE_AGGREGATION_MIN_NAME,
	GQL_OBJECT_TYPE_AGGREGATION_RANGE_NAME,
	GQL_OBJECT_TYPE_AGGREGATION_STATS_NAME,
	GQL_OBJECT_TYPE_AGGREGATION_TERMS_NAME,
	GQL_OBJECT_TYPE_AGGREGATIONS_UNION_NAME
} from './constants';


export function addStaticUnionTypes(glue) {
	const OBJECT_TYPE_AGGREGATION_COUNT = glue.getObjectType(GQL_OBJECT_TYPE_AGGREGATION_COUNT_NAME);
	const OBJECT_TYPE_AGGREGATION_DATE_HISTOGRAM = glue.getObjectType(GQL_OBJECT_TYPE_AGGREGATION_DATE_HISTOGRAM_NAME);
	const OBJECT_TYPE_AGGREGATION_DATE_RANGE = glue.getObjectType(GQL_OBJECT_TYPE_AGGREGATION_DATE_RANGE_NAME);
	const OBJECT_TYPE_AGGREGATION_GEO_DISTANCE = glue.getObjectType(GQL_OBJECT_TYPE_AGGREGATION_GEO_DISTANCE_NAME);
	const OBJECT_TYPE_AGGREGATION_MAX = glue.getObjectType(GQL_OBJECT_TYPE_AGGREGATION_MAX_NAME);
	const OBJECT_TYPE_AGGREGATION_MIN = glue.getObjectType(GQL_OBJECT_TYPE_AGGREGATION_MIN_NAME);
	const OBJECT_TYPE_AGGREGATION_RANGE = glue.getObjectType(GQL_OBJECT_TYPE_AGGREGATION_RANGE_NAME);
	const OBJECT_TYPE_AGGREGATION_STATS = glue.getObjectType(GQL_OBJECT_TYPE_AGGREGATION_STATS_NAME);
	const OBJECT_TYPE_AGGREGATION_TERMS = glue.getObjectType(GQL_OBJECT_TYPE_AGGREGATION_TERMS_NAME);

	glue.addUnionType({
		name: GQL_OBJECT_TYPE_AGGREGATIONS_UNION_NAME,
		typeResolver(source) {
			//log.debug(`source ${toStr(source)}`, source);
			switch (source.type) {
			case GQL_OBJECT_TYPE_AGGREGATION_COUNT_NAME: return OBJECT_TYPE_AGGREGATION_COUNT;
			case GQL_OBJECT_TYPE_AGGREGATION_DATE_HISTOGRAM_NAME: return OBJECT_TYPE_AGGREGATION_DATE_HISTOGRAM;
			case GQL_OBJECT_TYPE_AGGREGATION_DATE_RANGE_NAME: return OBJECT_TYPE_AGGREGATION_DATE_RANGE;
			case GQL_OBJECT_TYPE_AGGREGATION_GEO_DISTANCE_NAME: return OBJECT_TYPE_AGGREGATION_GEO_DISTANCE;
			case GQL_OBJECT_TYPE_AGGREGATION_MAX_NAME: return OBJECT_TYPE_AGGREGATION_MAX;
			case GQL_OBJECT_TYPE_AGGREGATION_MIN_NAME: return OBJECT_TYPE_AGGREGATION_MIN;
			case GQL_OBJECT_TYPE_AGGREGATION_RANGE_NAME: return OBJECT_TYPE_AGGREGATION_RANGE;
			case GQL_OBJECT_TYPE_AGGREGATION_STATS_NAME: return OBJECT_TYPE_AGGREGATION_STATS;
			case GQL_OBJECT_TYPE_AGGREGATION_TERMS_NAME: return OBJECT_TYPE_AGGREGATION_TERMS;
			default:
				throw new Error(`Unknown source.type:${source.type}in source:${toStr(source)}`);
			}
		},
		types: [
			OBJECT_TYPE_AGGREGATION_COUNT,
			OBJECT_TYPE_AGGREGATION_DATE_HISTOGRAM,
			OBJECT_TYPE_AGGREGATION_DATE_RANGE,
			OBJECT_TYPE_AGGREGATION_GEO_DISTANCE,
			OBJECT_TYPE_AGGREGATION_MIN,
			OBJECT_TYPE_AGGREGATION_MAX,
			OBJECT_TYPE_AGGREGATION_RANGE,
			OBJECT_TYPE_AGGREGATION_STATS,
			OBJECT_TYPE_AGGREGATION_TERMS
		]
	});
}
