import {
	AGGREGATION_COUNT,
	AGGREGATION_DATE_HISTOGRAM,
	AGGREGATION_DATE_RANGE,
	AGGREGATION_GEO_DISTANCE,
	AGGREGATION_MAX,
	AGGREGATION_MIN,
	AGGREGATION_RANGE,
	AGGREGATION_STATS,
	AGGREGATION_TERMS,
	toStr
} from '@enonic/js-utils';

import {
	OBJECT_TYPE_AGGREGATION_COUNT_NAME,
	OBJECT_TYPE_AGGREGATION_DATE_HISTOGRAM_NAME,
	OBJECT_TYPE_AGGREGATION_DATE_RANGE_NAME,
	OBJECT_TYPE_AGGREGATION_GEO_DISTANCE_NAME,
	OBJECT_TYPE_AGGREGATION_MAX_NAME,
	OBJECT_TYPE_AGGREGATION_MIN_NAME,
	OBJECT_TYPE_AGGREGATION_RANGE_NAME,
	OBJECT_TYPE_AGGREGATION_STATS_NAME,
	OBJECT_TYPE_AGGREGATION_TERMS_NAME
} from './types';


export function aggregationQueryTypeToGraphQLType(aggregationQueryType) {
	log.debug(`aggregationQueryType:${toStr(aggregationQueryType)}`);
	switch (aggregationQueryType) {
	case AGGREGATION_COUNT: return OBJECT_TYPE_AGGREGATION_COUNT_NAME;
	case AGGREGATION_DATE_HISTOGRAM: return OBJECT_TYPE_AGGREGATION_DATE_HISTOGRAM_NAME;
	case AGGREGATION_DATE_RANGE: return OBJECT_TYPE_AGGREGATION_DATE_RANGE_NAME;
	case AGGREGATION_GEO_DISTANCE: return OBJECT_TYPE_AGGREGATION_GEO_DISTANCE_NAME;
	case AGGREGATION_MAX: return OBJECT_TYPE_AGGREGATION_MAX_NAME;
	case AGGREGATION_MIN: return OBJECT_TYPE_AGGREGATION_MIN_NAME;
	case AGGREGATION_RANGE: return OBJECT_TYPE_AGGREGATION_RANGE_NAME;
	case AGGREGATION_STATS: return OBJECT_TYPE_AGGREGATION_STATS_NAME;
	case AGGREGATION_TERMS: return OBJECT_TYPE_AGGREGATION_TERMS_NAME;
	default:
		throw new Error(`Unknown aggregation query type:${aggregationQueryType}`);
	}
}
