name: Coverage

on: [ push ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout Lib Exporer
        uses: actions/checkout@v4
        with:
          repository: 'enonic/lib-explorer'
          path: 'symlinks/lib-explorer'

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install --frozen-lockfile --legacy-peer-deps

      - name: Test
        run: npm run cov

      - uses: codecov/codecov-action@v4
